export const CategoriesList = [
    "Growth",
    "Education",
    "Treasury" ,
    "Community",
    "DeFi",
    "NFTs",
    "Marketing",
    "Software Development",
    "Events",
    "Ecosystem",
    "Polkadot",
    "RWA",
    "Governance",
    "Infrastructure",
    "Deployment",
    "Operations",
    "XCM",
    "UI / UX",
    "Services",
    "Auditing",
    "Wallets",
    "Research",
    "General",
    "Democracy",
    "Staking",
    "Protocol"
  ]
